In [1]:
import numpy as np

In [2]:
labelfile = "data/sentimentLabels.txt"
reviewfile = "data/sentimentReviews.txt"

In [3]:
with open(labelfile,'r') as f:
    labelsRaw = f.read()
with open(reviewfile,'r') as f:
    reviewsRaw = f.read()

In [4]:
from string import punctuation

reviewsWithouTPunct = ''.join (c for c in reviewsRaw if c not in punctuation or c =='.')
print (reviewsWithouTPunct[:100])

bromwell high is a cartoon comedy . it ran at the same time as some other programs about school life


# pre processing

In [5]:
labels = labelsRaw.splitlines()
revs = reviewsWithouTPunct.splitlines()

all_words= list()

reviews = list()
for review in revs:
    reviews.append(review.split())
    all_words += reviews[-1]


print(labels[:2])
print(reviews[:2])

['positive', 'negative']
[['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', '.', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', '.', 'my', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'bromwell', 'high', 's', 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', 'teachers', '.', 'the', 'scramble', 'to', 'survive', 'financially', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', 'teachers', 'pomp', 'the', 'pettiness', 'of', 'the', 'whole', 'situation', 'all', 'remind', 'me', 'of', 'the', 'schools', 'i', 'knew', 'and', 'their', 'students', '.', 'when', 'i', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school', 'i', 'immediately', 'recalled', '.', '.', '.', '.', '.', '.', '.', '.', '.', 'at', '.', '.', '.', '.', '.', '.', '.', '.', '.', '.', 'hi

In [6]:
print (len(set(all_words)))
print(all_words[:100])

74073
['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', '.', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', '.', 'my', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'bromwell', 'high', 's', 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', 'teachers', '.', 'the', 'scramble', 'to', 'survive', 'financially', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', 'teachers', 'pomp', 'the', 'pettiness', 'of', 'the', 'whole', 'situation', 'all', 'remind', 'me', 'of', 'the', 'schools', 'i', 'knew', 'and', 'their', 'students', '.', 'when', 'i', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school', 'i']


In [7]:
from collections import Counter
c = Counter(all_words)
srt = c.most_common()
print ("number of unique words:", len(srt))
print ("the most repeated words:", srt[:10])
print ("some least repeated words", srt[-2:])

number of unique words: 74073
the most repeated words: [('the', 336713), ('.', 327192), ('and', 164107), ('a', 163009), ('of', 145864), ('to', 135720), ('is', 107328), ('br', 101872), ('it', 96352), ('in', 93968)]
some least repeated words [('whelk', 1), ('hued', 1)]


In [8]:
vocab = [word for word,_ in srt]
print ("vocab sample" , vocab[:10])

vocab sample ['the', '.', 'and', 'a', 'of', 'to', 'is', 'br', 'it', 'in']


In [9]:
word2int = {word: i+1 for i,word in enumerate(vocab)}
int2word = {i+1: word for i,word in enumerate(vocab)}

In [10]:
# encode reviews
reviews_int = [[word2int[w] for w in review] for review in reviews]

In [11]:
print(word2int[reviews[0][0]])
print(reviews_int[:2])

21026
[[21026, 309, 7, 4, 1051, 208, 2, 9, 2139, 33, 1, 172, 58, 16, 50, 82, 5786, 45, 383, 111, 141, 16, 5195, 2, 61, 155, 10, 1, 4976, 5853, 476, 72, 6, 261, 13, 21026, 309, 14, 1979, 7, 75, 2396, 6, 614, 74, 7, 5195, 2, 1, 24104, 6, 1984, 10167, 1, 5787, 1500, 37, 52, 67, 205, 146, 68, 1200, 5195, 19870, 1, 37443, 5, 1, 222, 884, 32, 2989, 72, 5, 1, 5788, 11, 687, 3, 68, 1500, 2, 55, 11, 217, 1, 384, 10, 63, 4, 1407, 3687, 784, 6, 3484, 181, 1, 383, 11, 1213, 13584, 2, 2, 2, 2, 2, 2, 2, 2, 2, 33, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 309, 2, 4, 350, 342, 2914, 11, 144, 128, 6, 7691, 31, 5, 130, 5195, 2, 1407, 2327, 6, 21026, 309, 2, 11, 529, 13, 110, 1449, 5, 61, 544, 103, 13, 21026, 309, 7, 228, 4147, 2, 49, 4, 2212, 13, 9, 216, 24], [64, 5, 4, 126, 37, 48, 7473, 1396, 17, 4, 4182, 2, 506, 46, 18, 4, 623, 135, 13, 7, 4, 1280, 458, 5, 1722, 208, 2, 4, 10625, 7374, 301, 7, 668, 84, 36, 2117, 1087, 2990, 35, 1, 899, 46418, 5, 9, 14, 5097, 2, 465, 9, 2657, 1722, 1, 222, 58, 18, 59, 795, 1298, 

In [12]:
print(type(reviews_int[0]))

<class 'list'>


In [13]:
# encode labels
enc_labels = [1.0 if la =='positive' else 0.0 for la in labels]

In [14]:
print(enc_labels[:10])
print(labels[:10])

[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]
['positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative']


In [15]:
# remove outliers
review_lens = Counter([len(x) for x in reviews_int])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))
print("total reviews:", len(reviews_int))

min_len = 20
idx_desired_date = [idx for idx, rev in enumerate(reviews_int) if len(rev) >= min_len]
print("{} samples with minimum length of {}".format(len(idx_desired_date), min_len))

filtered_revs = [reviews_int[idx] for idx in idx_desired_date ]
filtered_labels = [enc_labels[idx] for idx in idx_desired_date ]

reviews_int = filtered_revs
enc_labels = filtered_labels

Zero-length reviews: 0
Maximum review length: 2633
total reviews: 25000
24989 samples with minimum length of 20


In [16]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)

    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [17]:
# Test your implementation!

seq_length = 200

features = pad_features(reviews_int, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_int), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
l = features[:30,:10]
print(np.array(l))

[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [22383    43 46419    16   707 17140  3390    48    78    36]
 [ 4506   506    16     4  3343   163  8313  1653     7  4820]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   55    11    15   117    61   799   553    72   365     6]
 [    0     0    12   216    24     1  1687  2070  1566   868]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    1   331   579    35     4   163   749  2732    10   326]
 [   10    12 10172  5306  1947   690   445    23   281   674]
 [    0     0     0     0     0     0     0     0     0

In [18]:
# split data
split_frac = 0.8
encoded_labels = np.array(enc_labels,dtype=np.float64)

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]



## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(19991, 200) 
Validation set: 	(2499, 200) 
Test set: 		(2499, 200)


In [19]:
print(type(train_x), train_x.shape, type(train_y), train_y.shape)
print(type(val_x), val_x.shape, type(val_y), val_y.shape)
print(type(test_x), test_x.shape, type(test_y), test_y.shape)

<class 'numpy.ndarray'> (19991, 200) <class 'numpy.ndarray'> (19991,)
<class 'numpy.ndarray'> (2499, 200) <class 'numpy.ndarray'> (2499,)
<class 'numpy.ndarray'> (2499, 200) <class 'numpy.ndarray'> (2499,)


In [20]:
from torch.utils.data import TensorDataset, DataLoader
import torch
print(torch.__version__)
import torch.nn as nn

1.0.0


In [21]:
# dataset
batch_size = 1024
tr = int(train_x.shape[0]/batch_size)*batch_size
va = int(val_x.shape[0]/batch_size)*batch_size
te = int(test_x.shape[0]/batch_size)*batch_size

train_data = TensorDataset(torch.from_numpy(train_x[:tr]),torch.from_numpy(train_y[:tr]))
valid_data = TensorDataset(torch.from_numpy(val_x[:va]),torch.from_numpy(val_y[:va]))
test_data = TensorDataset(torch.from_numpy(test_x[:te]),torch.from_numpy(test_y[:te]))


train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [22]:
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([1024, 200])
Sample input: 
 tensor([[    0,     0,     0,  ...,    24,    67,     9],
        [    0,     0,     0,  ...,     4,   153,     2],
        [    0,     0,     0,  ...,    18,    12,     2],
        ...,
        [   11,    40,    12,  ...,     3, 18211,  8117],
        [    0,     0,     0,  ...,    10,   335,     2],
        [    0,     0,     0,  ...,    17,    19,  4319]])

Sample label size:  torch.Size([1024])
Sample label: 
 tensor([0., 0., 0.,  ..., 1., 0., 1.], dtype=torch.float64)


In [23]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print (device)
train_on_gpu = torch.cuda.is_available()

cuda:0


In [24]:
class SentimentRNN(nn.Module):
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        super(SentimentRNN, self).__init__()
        self.output_szie = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        #define layers
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.LSTM(embedding_dim,
                           hidden_dim,
                           n_layers, 
                           batch_first = True, 
                           dropout = drop_prob)
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, x, hidden):
        batch_size = x.size(0)
#         print ("x.size(0)", x.size(0))
        
        embeds = self.embedding(x)
        lstm_out, hidden = self.rnn(embeds, hidden)
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        out = self.fc(lstm_out)
        sig_out = self.sigmoid(out)
        
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1]

        return sig_out, hidden
    
    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device))
        
        return hidden

In [25]:
vocab_size = len(vocab)+1 # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2
net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
print(net)

SentimentRNN(
  (embedding): Embedding(74074, 400)
  (rnn): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [26]:
lr = 0.001
criterion  = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)

In [27]:
epochs = 10
counter = 0
print_every = 25
clip = 5 # gradient clipping

net = net.to(device)
net.train()

for e in range(epochs):
    h = net.init_hidden(batch_size)
    # batch loop
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        
        if (inputs.size(0)!= batch_size):
            print("inputs.size(0)",inputs.size(0))
            continue
            

        h = tuple([each.data for each in h])
        #print([each.size(1) for each in h])
        net.zero_grad()
        output, h = net(inputs,h)
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()
        counter = counter + 1

        if counter % print_every == 0:
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:
                val_h = tuple([each.data for each in val_h])
                inputs, labels = inputs.to(device), labels.to(device)
                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())
                val_losses.append(val_loss.item())
            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 2/10... Step: 25... Loss: 0.626456... Val Loss: 0.634351
Epoch: 3/10... Step: 50... Loss: 0.554207... Val Loss: 0.569299
Epoch: 4/10... Step: 75... Loss: 0.455695... Val Loss: 0.525918
Epoch: 6/10... Step: 100... Loss: 0.418175... Val Loss: 0.502986
Epoch: 7/10... Step: 125... Loss: 0.706977... Val Loss: 0.599667
Epoch: 8/10... Step: 150... Loss: 0.339981... Val Loss: 0.500383
Epoch: 10/10... Step: 175... Loss: 0.299648... Val Loss: 0.522988


In [28]:
# Get test data loss and accuracy

test_losses = [] # track loss
num_correct = 0

# init hidden state
h = net.init_hidden(batch_size)

net.eval()
# iterate over test data
for inputs, labels in test_loader:

    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])


    inputs, labels = inputs.to(device), labels.to(device)
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)


# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

Test loss: 0.489
Test accuracy: 0.795


In [36]:
# negative test review
test_review_neg = 'The worst movie I have seen; acting was terrible and I want my money back . This movie had bad acting and the dialogue was slow .'

from string import punctuation

def tokenize_review(test_review):
    test_review = test_review.lower() # lowercase
    # get rid of punctuation
    test_text = ''.join([c for c in test_review if c not in punctuation])

    # splitting by spaces
    test_words = test_text.split()

    # tokens
    test_ints = []
    test_ints.append([ word2int[word] for word in test_words])

    return test_ints

# test code and generate tokenized review
test_ints = tokenize_review(test_review_neg)
print(test_ints)

[[1, 248, 19, 11, 29, 109, 114, 15, 389, 3, 11, 182, 61, 274, 145, 12, 19, 69, 77, 114, 3, 1, 411, 15, 540]]


In [37]:
seq_length=200
features = pad_features(test_ints, seq_length)

print(features)

[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
    0   0   0   0   0   0   0   0   0   0   0   0   0   1 248  19  11  29
  109 114  15 389   3  11 182  61 274 145  12  19  69  77 114   3   1 411
   15 540]]


In [38]:
feature_tensor = torch.from_numpy(features)
print(feature_tensor.size())

torch.Size([1, 200])


In [39]:
def predict(net, test_review, sequence_length=200):
    
    net.eval()
    
    # tokenize review
    test_ints = tokenize_review(test_review)
    
    # pad tokenized sequence
    seq_length=sequence_length
    features = pad_features(test_ints, seq_length)
    
    # convert to tensor to pass into your model
    feature_tensor = torch.from_numpy(features)
    
    batch_size = feature_tensor.size(0)
    
    # initialize hidden state
    h = net.init_hidden(batch_size)
    
    if(train_on_gpu):
        feature_tensor = feature_tensor.cuda()
    
    # get the output from the model
    output, h = net(feature_tensor, h)
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze()) 
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))
    
    # print custom response
    if(pred.item()==1):
        print("Positive review detected!")
    else:
        print("Negative review detected.")
        

In [54]:
# positive test review
test_review_pos = 'This movie had the best acting and the dialogue was so good'
# call function
seq_length=200 # good to use the length that was trained on

predict(net, test_review_pos, seq_length)

Prediction value, pre-rounding: 0.944326
Positive review detected!
