In [1]:
import numpy as np

In [2]:
labelfile = "data/sentimentLabels.txt"
reviewfile = "data/sentimentReviews.txt"

In [3]:
with open(labelfile,'r') as f:
    labelsRaw = f.read()
with open(reviewfile,'r') as f:
    reviewsRaw = f.read()

In [4]:
from string import punctuation

reviewsWithouTPunct = ''.join (c for c in reviewsRaw if c not in punctuation ) # or c =='.'
print (reviewsWithouTPunct[:100])

bromwell high is a cartoon comedy  it ran at the same time as some other programs about school life 


# pre processing

In [5]:
labels = labelsRaw.splitlines()
revs = reviewsWithouTPunct.splitlines()

all_words= list()

reviews = list()
for review in revs:
    reviews.append(review.split())
    all_words += reviews[-1]


print(labels[:2])
print(reviews[:2])

['positive', 'negative']
[['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', 'my', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'bromwell', 'high', 's', 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', 'teachers', 'the', 'scramble', 'to', 'survive', 'financially', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', 'teachers', 'pomp', 'the', 'pettiness', 'of', 'the', 'whole', 'situation', 'all', 'remind', 'me', 'of', 'the', 'schools', 'i', 'knew', 'and', 'their', 'students', 'when', 'i', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school', 'i', 'immediately', 'recalled', 'at', 'high', 'a', 'classic', 'line', 'inspector', 'i', 'm', 'here', 'to', 'sack', 'one', 'of', 'your', 'teachers', 'student

In [6]:
print (len(set(all_words)))
print(all_words[:100])

74072
['bromwell', 'high', 'is', 'a', 'cartoon', 'comedy', 'it', 'ran', 'at', 'the', 'same', 'time', 'as', 'some', 'other', 'programs', 'about', 'school', 'life', 'such', 'as', 'teachers', 'my', 'years', 'in', 'the', 'teaching', 'profession', 'lead', 'me', 'to', 'believe', 'that', 'bromwell', 'high', 's', 'satire', 'is', 'much', 'closer', 'to', 'reality', 'than', 'is', 'teachers', 'the', 'scramble', 'to', 'survive', 'financially', 'the', 'insightful', 'students', 'who', 'can', 'see', 'right', 'through', 'their', 'pathetic', 'teachers', 'pomp', 'the', 'pettiness', 'of', 'the', 'whole', 'situation', 'all', 'remind', 'me', 'of', 'the', 'schools', 'i', 'knew', 'and', 'their', 'students', 'when', 'i', 'saw', 'the', 'episode', 'in', 'which', 'a', 'student', 'repeatedly', 'tried', 'to', 'burn', 'down', 'the', 'school', 'i', 'immediately', 'recalled', 'at', 'high']


In [7]:
from collections import Counter
c = Counter(all_words)
srt = c.most_common()
print ("number of unique words:", len(srt))
print ("the most repeated words:", srt[:10])
print ("some least repeated words", srt[-2:])

number of unique words: 74072
the most repeated words: [('the', 336713), ('and', 164107), ('a', 163009), ('of', 145864), ('to', 135720), ('is', 107328), ('br', 101872), ('it', 96352), ('in', 93968), ('i', 87623)]
some least repeated words [('whelk', 1), ('hued', 1)]


In [8]:
vocab = [word for word,_ in srt]
print ("vocab sample" , vocab[:10])

vocab sample ['the', 'and', 'a', 'of', 'to', 'is', 'br', 'it', 'in', 'i']


In [9]:
word2int = {word: i+1 for i,word in enumerate(vocab)}
int2word = {i+1: word for i,word in enumerate(vocab)}

In [10]:
# encode reviews
reviews_int = [[word2int[w] for w in review] for review in reviews]

In [11]:
print(word2int[reviews[0][0]])
print(reviews_int[:2])

21025
[[21025, 308, 6, 3, 1050, 207, 8, 2138, 32, 1, 171, 57, 15, 49, 81, 5785, 44, 382, 110, 140, 15, 5194, 60, 154, 9, 1, 4975, 5852, 475, 71, 5, 260, 12, 21025, 308, 13, 1978, 6, 74, 2395, 5, 613, 73, 6, 5194, 1, 24103, 5, 1983, 10166, 1, 5786, 1499, 36, 51, 66, 204, 145, 67, 1199, 5194, 19869, 1, 37442, 4, 1, 221, 883, 31, 2988, 71, 4, 1, 5787, 10, 686, 2, 67, 1499, 54, 10, 216, 1, 383, 9, 62, 3, 1406, 3686, 783, 5, 3483, 180, 1, 382, 10, 1212, 13583, 32, 308, 3, 349, 341, 2913, 10, 143, 127, 5, 7690, 30, 4, 129, 5194, 1406, 2326, 5, 21025, 308, 10, 528, 12, 109, 1448, 4, 60, 543, 102, 12, 21025, 308, 6, 227, 4146, 48, 3, 2211, 12, 8, 215, 23], [63, 4, 3, 125, 36, 47, 7472, 1395, 16, 3, 4181, 505, 45, 17, 3, 622, 134, 12, 6, 3, 1279, 457, 4, 1721, 207, 3, 10624, 7373, 300, 6, 667, 83, 35, 2116, 1086, 2989, 34, 1, 898, 46417, 4, 8, 13, 5096, 464, 8, 2656, 1721, 1, 221, 57, 17, 58, 794, 1297, 832, 228, 8, 43, 98, 123, 1469, 59, 147, 38, 1, 963, 142, 29, 667, 123, 1, 13584, 410, 61, 9

In [12]:
print(type(reviews_int[0]))

<class 'list'>


In [13]:
# encode labels
enc_labels = [1.0 if la =='positive' else 0.0 for la in labels]

In [14]:
print(enc_labels[:10])
print(labels[:10])

[1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0, 1.0, 0.0]
['positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative', 'positive', 'negative']


In [15]:
# remove outliers
review_lens = Counter([len(x) for x in reviews_int])
print("Zero-length reviews: {}".format(review_lens[0]))
print("Maximum review length: {}".format(max(review_lens)))
print("total reviews:", len(reviews_int))

min_len = 1
idx_desired_date = [idx for idx, rev in enumerate(reviews_int) if len(rev) >= min_len]
print("{} samples with minimum length of {}".format(len(idx_desired_date), min_len))

filtered_revs = [reviews_int[idx] for idx in idx_desired_date ]
filtered_labels = [enc_labels[idx] for idx in idx_desired_date ]

reviews_int = filtered_revs
enc_labels = filtered_labels

Zero-length reviews: 0
Maximum review length: 2514
total reviews: 25000
25000 samples with minimum length of 1


In [16]:
def pad_features(reviews_ints, seq_length):
    ''' Return features of review_ints, where each review is padded with 0's 
        or truncated to the input seq_length.
    '''
    
    # getting the correct rows x cols shape
    features = np.zeros((len(reviews_ints), seq_length), dtype=int)

    # for each review, I grab that review and 
    for i, row in enumerate(reviews_ints):
        features[i, -len(row):] = np.array(row)[:seq_length]
    
    return features

In [17]:
# Test your implementation!

seq_length = 200

features = pad_features(reviews_int, seq_length=seq_length)

## test statements - do not change - ##
assert len(features)==len(reviews_int), "Your features should have as many rows as reviews."
assert len(features[0])==seq_length, "Each feature row should contain seq_length values."

# print first 10 values of the first 30 batches 
l = features[:30,:10]
print(np.array(l))

[[    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [22382    42 46418    15   706 17139  3389    47    77    35]
 [ 4505   505    15     3  3342   162  8312  1652     6  4819]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [   54    10    14   116    60   798   552    71   364     5]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    0     0     0     0     0     0     0     0     0     0]
 [    1   330   578    34     3   162   748  2731     9   325]
 [    9    11 10171  5305  1946   689   444    22   280   673]
 [    0     0     0     0     0     0     0     0     0

In [18]:
# split data
split_frac = 0.8
encoded_labels = np.array(enc_labels,dtype=np.float64)

## split data into training, validation, and test data (features and labels, x and y)

split_idx = int(len(features)*split_frac)
train_x, remaining_x = features[:split_idx], features[split_idx:]
train_y, remaining_y = encoded_labels[:split_idx], encoded_labels[split_idx:]

test_idx = int(len(remaining_x)*0.5)
val_x, test_x = remaining_x[:test_idx], remaining_x[test_idx:]
val_y, test_y = remaining_y[:test_idx], remaining_y[test_idx:]



## print out the shapes of your resultant feature data
print("\t\t\tFeature Shapes:")
print("Train set: \t\t{}".format(train_x.shape), 
      "\nValidation set: \t{}".format(val_x.shape),
      "\nTest set: \t\t{}".format(test_x.shape))

			Feature Shapes:
Train set: 		(20000, 200) 
Validation set: 	(2500, 200) 
Test set: 		(2500, 200)


In [19]:
print(type(train_x), train_x.shape, type(train_y), train_y.shape)
print(type(val_x), val_x.shape, type(val_y), val_y.shape)
print(type(test_x), test_x.shape, type(test_y), test_y.shape)

<class 'numpy.ndarray'> (20000, 200) <class 'numpy.ndarray'> (20000,)
<class 'numpy.ndarray'> (2500, 200) <class 'numpy.ndarray'> (2500,)
<class 'numpy.ndarray'> (2500, 200) <class 'numpy.ndarray'> (2500,)


In [20]:
from torch.utils.data import TensorDataset, DataLoader
import torch
print(torch.__version__)
import torch.nn as nn

1.0.0


In [21]:
# dataset
batch_size = 1024
tr = int(train_x.shape[0]/batch_size)*batch_size
va = int(val_x.shape[0]/batch_size)*batch_size
te = int(test_x.shape[0]/batch_size)*batch_size

train_data = TensorDataset(torch.from_numpy(train_x[:tr]),torch.from_numpy(train_y[:tr]))
valid_data = TensorDataset(torch.from_numpy(val_x[:va]),torch.from_numpy(val_y[:va]))
test_data = TensorDataset(torch.from_numpy(test_x[:te]),torch.from_numpy(test_y[:te]))


train_loader = DataLoader(train_data, shuffle=True, batch_size=batch_size)
valid_loader = DataLoader(valid_data, shuffle=True, batch_size=batch_size)
test_loader = DataLoader(test_data, shuffle=True, batch_size=batch_size)

In [22]:
dataiter = iter(train_loader)
sample_x, sample_y = dataiter.next()

print('Sample input size: ', sample_x.size()) # batch_size, seq_length
print('Sample input: \n', sample_x)
print()
print('Sample label size: ', sample_y.size()) # batch_size
print('Sample label: \n', sample_y)

Sample input size:  torch.Size([1024, 200])
Sample input: 
 tensor([[  596,    37,    10,  ...,  7766,     9,    20],
        [    0,     0,     0,  ...,     8,     3,   348],
        [  255,   108,     2,  ...,     4,     1,  2929],
        ...,
        [    0,     0,     0,  ...,    89,    23,  1393],
        [   60,   311,     2,  ...,   883,     2,  1957],
        [11721,     6,     3,  ...,    21,    66,     6]])

Sample label size:  torch.Size([1024])
Sample label: 
 tensor([1., 1., 1.,  ..., 0., 0., 1.], dtype=torch.float64)


In [23]:
device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu")
print (device)
train_on_gpu = torch.cuda.is_available()

cuda:0


In [24]:
class SentimentRNN(nn.Module):
    def __init__(self, vocab_size, output_size, embedding_dim, hidden_dim, n_layers, drop_prob=0.5):
        super(SentimentRNN, self).__init__()
        self.output_szie = output_size
        self.n_layers = n_layers
        self.hidden_dim = hidden_dim
        
        #define layers
        
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.rnn = nn.LSTM(embedding_dim,
                           hidden_dim,
                           n_layers, 
                           batch_first = True, 
                           dropout = drop_prob)
        self.fc = nn.Linear(hidden_dim, output_size)
        self.sigmoid = nn.Sigmoid()
        
        
    def forward(self, x, hidden):
        batch_size = x.size(0)
#         print ("x.size(0)", x.size(0))
        
        embeds = self.embedding(x)
        lstm_out, hidden = self.rnn(embeds, hidden)
        lstm_out = lstm_out.contiguous().view(-1, self.hidden_dim)
        
        out = self.fc(lstm_out)
        sig_out = self.sigmoid(out)
        
        sig_out = sig_out.view(batch_size, -1)
        sig_out = sig_out[:, -1]

        return sig_out, hidden
    
    def init_hidden(self, batch_size):
        weight = next(self.parameters()).data
        hidden = (weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device),
                  weight.new(self.n_layers, batch_size, self.hidden_dim).zero_().to(device))
        
        return hidden

In [25]:
vocab_size = len(vocab)+1 # +1 for the 0 padding + our word tokens
output_size = 1
embedding_dim = 400
hidden_dim = 256
n_layers = 2
net = SentimentRNN(vocab_size, output_size, embedding_dim, hidden_dim, n_layers)
print(net)

SentimentRNN(
  (embedding): Embedding(74073, 400)
  (rnn): LSTM(400, 256, num_layers=2, batch_first=True, dropout=0.5)
  (fc): Linear(in_features=256, out_features=1, bias=True)
  (sigmoid): Sigmoid()
)


In [26]:
lr = 0.001
criterion  = nn.BCELoss()
optimizer = torch.optim.Adam(net.parameters(), lr=lr)

In [ ]:
epochs = 11
counter = 0
print_every = 10
clip = 5 # gradient clipping

net = net.to(device)
net.train()

for e in range(epochs):
    
    # batch loop
    for inputs, labels in train_loader:
        inputs, labels = inputs.to(device), labels.to(device)
        
        h = net.init_hidden(inputs.size(0))
        
#         if (inputs.size(0)!= batch_size):
#             print("inputs.size(0)",inputs.size(0))
#             continue
            

#        h = tuple([each.data for each in h])
        #print([each.size(1) for each in h])
        net.zero_grad()
        output, h = net(inputs,h)
        loss = criterion(output.squeeze(), labels.float())
        loss.backward()
        nn.utils.clip_grad_norm_(net.parameters(), clip)
        optimizer.step()
        counter = counter + 1

        if counter % print_every == 0:
            val_h = net.init_hidden(batch_size)
            val_losses = []
            net.eval()
            for inputs, labels in valid_loader:
                val_h = tuple([each.data for each in val_h])
                inputs, labels = inputs.to(device), labels.to(device)
                output, val_h = net(inputs, val_h)
                val_loss = criterion(output.squeeze(), labels.float())
                val_losses.append(val_loss.item())
            net.train()
            print("Epoch: {}/{}...".format(e+1, epochs),
                  "Step: {}...".format(counter),
                  "Loss: {:.6f}...".format(loss.item()),
                  "Val Loss: {:.6f}".format(np.mean(val_losses)))

Epoch: 1/11... Step: 10... Loss: 0.671417... Val Loss: 0.668857
Epoch: 2/11... Step: 20... Loss: 0.631050... Val Loss: 0.598597
Epoch: 2/11... Step: 30... Loss: 0.557314... Val Loss: 0.583781
Epoch: 3/11... Step: 40... Loss: 0.522381... Val Loss: 0.508045
Epoch: 3/11... Step: 50... Loss: 0.508589... Val Loss: 0.544021
Epoch: 4/11... Step: 60... Loss: 0.426985... Val Loss: 0.506075
Epoch: 4/11... Step: 70... Loss: 0.426870... Val Loss: 0.474492
Epoch: 5/11... Step: 80... Loss: 0.370317... Val Loss: 0.444556


In [ ]:
# Get test data loss and accuracy

test_losses = [] # track loss
num_correct = 0

# init hidden state
h = net.init_hidden(batch_size)

net.eval()
# iterate over test data
for inputs, labels in test_loader:

    # Creating new variables for the hidden state, otherwise
    # we'd backprop through the entire training history
    h = tuple([each.data for each in h])


    inputs, labels = inputs.to(device), labels.to(device)
    
    # get predicted outputs
    output, h = net(inputs, h)
    
    # calculate loss
    test_loss = criterion(output.squeeze(), labels.float())
    test_losses.append(test_loss.item())
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze())  # rounds to the nearest integer
    
    # compare predictions to true label
    correct_tensor = pred.eq(labels.float().view_as(pred))
    correct = np.squeeze(correct_tensor.numpy()) if not train_on_gpu else np.squeeze(correct_tensor.cpu().numpy())
    num_correct += np.sum(correct)


# -- stats! -- ##
# avg test loss
print("Test loss: {:.3f}".format(np.mean(test_losses)))

# accuracy over all test data
test_acc = num_correct/len(test_loader.dataset)
print("Test accuracy: {:.3f}".format(test_acc))

In [ ]:
# negative test review
test_review_neg = 'The worst movie I have seen; acting was terrible and I want my money back . This movie had bad acting and the dialogue was slow .'

from string import punctuation

def tokenize_review(test_review):
    test_review = test_review.lower() # lowercase
    # get rid of punctuation
    test_text = ''.join([c for c in test_review if c not in punctuation])

    # splitting by spaces
    test_words = test_text.split()

    # tokens
    test_ints = []
    test_ints.append([ word2int[word] for word in test_words])

    return test_ints

# test code and generate tokenized review
test_ints = tokenize_review(test_review_neg)
print(test_ints)

In [ ]:
seq_length=200
features = pad_features(test_ints, seq_length)

print(features)

In [ ]:
feature_tensor = torch.from_numpy(features)
print(feature_tensor.size())

In [ ]:
def predict(net, test_review, sequence_length=200):
    
    net.eval()
    
    # tokenize review
    test_ints = tokenize_review(test_review)
    
    # pad tokenized sequence
    seq_length=sequence_length
    features = pad_features(test_ints, seq_length)
    
    # convert to tensor to pass into your model
    feature_tensor = torch.from_numpy(features)
    
    batch_size = feature_tensor.size(0)
    
    # initialize hidden state
    h = net.init_hidden(batch_size)
    
    if(train_on_gpu):
        feature_tensor = feature_tensor.cuda()
    
    # get the output from the model
    output, h = net(feature_tensor, h)
    
    # convert output probabilities to predicted class (0 or 1)
    pred = torch.round(output.squeeze()) 
    # printing output value, before rounding
    print('Prediction value, pre-rounding: {:.6f}'.format(output.item()))
    
    # print custom response
    if(pred.item()==1):
        print("Positive review detected!")
    else:
        print("Negative review detected.")
        

In [ ]:
# positive test review
test_review_pos = 'I hate the movie .'
# call function
seq_length=200 # good to use the length that was trained on

predict(net, test_review_pos, seq_length)